[project]
name = "memento-cli"
version = "0.0.6"
description = "Examine snapshots in web archives such as the Internet Archive's Wayback Machine"
authors = [
    { name = "Ed Summers", email = "ehs@pobox.com" },
]
license = "MIT"
readme = "README.md"
packages = [{include = "memento_cli"}]
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.7",
    "selenium>=4.12.0",
    "requests>=2.31.0"
]

[project.urls]
Homepage = "https://github.com/edsu/memento-cli"

[project.scripts]
memento = "memento_cli:main"

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.15.15",
]
