name: Tests
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: Install python
      run: uv python install

    - name: Check formatting
      run: uv run ruff format --exit-non-zero-on-format

    - name: Test with pytest
      run: uv run pytest -v
